// DO NOT EDIT THIS FILE
import java.util.ArrayList;
import java.util.Collections;
import java.util.Hashtable;
import java.util.List;

/**
 * An Assignment assigns values to some or all variables of a CSP.
 * 
 * 
 */

public class Assignment 
{
	
	/**
	 * List containing all assigned variables. Positions reflect the the order in which
	 * the variables were assigned to values.
	 */
	List<Variable> variables;
	
	
	/** Maps variables to their assigned values. */
	Hashtable<Variable, Object> variableToValue;

	// Constructor
	public Assignment() {
		variables = new ArrayList<Variable>();
		variableToValue = new Hashtable<Variable, Object>();
	}

	// Return all Variables that are assigned values
	public List<Variable> getVariables() {
		return Collections.unmodifiableList(variables);
	}

	// Return the assigned value of a particular Variable
	public Object getAssignment(Variable var) {
		return variableToValue.get(var);
	}

	// Assign a value to a particular Variable
	public void setAssignment(Variable var, Object value) {
		if (!variableToValue.containsKey(var))
			variables.add(var);
		variableToValue.put(var, value);
	}
    
	// Remove assigned value for a particular Variable
	public void removeAssignment(Variable var) {
		if (hasAssignmentFor(var)) {
			variables.remove(var);
			variableToValue.remove(var);
		}
	}

	// Check if a Variable has an assigned value
	public boolean hasAssignmentFor(Variable var) {
		return variableToValue.get(var) != null;
	}

	

}
