// DO NOT EDIT THIS FILE
import java.util.List;

// A simple interface that any constraint class must implement.
public interface Constraint
{
			
	// check whether particular variable assignments
	// satisfy the constraint.
	boolean constraintIsSatisfied(Assignment asn);
	
	// return the variables in the constraint's scope
	public List<Variable> getVariables();
	
	// get the ID of the constraint
	public String getID();
	
	
	
}
