// DO NOT EDIT THIS FILE
import java.util.ArrayList;
import java.util.List;

/*
 * A unary Constraint that says a particular individual Variable cannot have certain values.
 */
public class InvalidUnaryValueConstraint implements Constraint

{
    // A single Variable (unary)
	private Variable var1;
	private List<Variable> variablesInScope;
	private String constraintID;

	// Constructor
	public InvalidUnaryValueConstraint(String cid, Variable var1)
	{
		constraintID = cid;
		this.var1 = var1;
		variablesInScope = new ArrayList<Variable>(1);
		variablesInScope.add(var1);
		for (Variable v : variablesInScope)
		{
			v.addConstraint(this);
		}
	}

	public String getID()
	{
		return constraintID;
	}

	public List<Variable> getVariables()
	{
		return variablesInScope;
	}

	/*
	 * This particular Constraint is only satisfied if the Variable
	 * has a value less than 4. 
	 */
	public boolean constraintIsSatisfied(Assignment asn)
	{
		Integer val1 = (Integer) asn.getAssignment(var1);
		return (val1 < 4);
	}

	public String toString()
	{
		return constraintID;
	}

}
