// DO NOT EDIT THIS FILE
import java.util.ArrayList;
import java.util.List;

/*
 * A simple class representing variables.
 * A variable is associated with a domain (values it can take)
 * and may be involved with constraints.
 */
public class Variable
{
	// simple String ID for a Variable
	private String variableID;
	
	// List of values a Variable can take
	private List<Object> variableDomain;
	
	// Constraints the Variable is involved in
	private List<Constraint> constraints;

	// constructor
	public Variable(String vid, List<Object> domain)
	{
		variableID = vid;
		variableDomain = domain;
		constraints = new ArrayList<Constraint>();
	}

	// A variety of getters and setters
	public String getID()
	{
		return variableID;
	}

	public List<Object> getDomain()
	{
		return variableDomain;
	}

	public void setDomain(List<Object> domain)
	{
		variableDomain = domain;
	}

	public void addConstraint(Constraint c)
	{
		constraints.add(c);
	}

	public List<Constraint> getConstraints()
	{
		return constraints;
	}

	// Two Variables are equal if they have the same ID
	public boolean equals(Object obj)
	{
		if (obj == null)
			return false;
		if (obj == this)
			return true;
		if (obj.getClass() != getClass())
			return false;

		Variable rhs = (Variable) obj;
		return (this.variableID.equals(rhs.getID()));
	}
	
	// Just a String representation of a Variable
	public String toString()
	{
		String s = "";
		s += variableID;
		for (Object o: variableDomain)
		{
			s += " "+o;
		}
		return s;
	}

}
